#!/bin/bash

# Build the container
echo "Building Slashrtc Webapi..."
docker build -t slashrtc:simple .
echo "Built Slashrtc Webapi..."

# Run the built image as a container
docker run --name slashrtc-simple --rm -d slashrtc:simple
echo "Slashrtc Webapi container started"

# Get the value of app version
VERSION=$(docker inspect --format='{{ index .Config.Labels "in.slashrtc.webapi.version"}}' slashrtc:simple)
echo "Version: $VERSION"

# Tag the image with version number
docker tag slashrtc:simple slashrtc:$VERSION
echo "Image tagged as slashrtc:$VERSION"

# Stop the container
docker stop slashrtc-simple
echo "Slashrtc Webapi container stopped"
