#!/bin/bash

# Build the container
echo "Building Webapi..."
docker build -t webapi:tmp .
echo "Built Webapi..."

# Run the built image as a container
docker run --name webapi-tmp --rm -d webapi:tmp
echo "Webapi container started"

# Get the value of app version
VERSION=$(docker inspect --format='{{ index .Config.Labels "in.tutorial.webapi.version"}}' webapi:tmp)
echo "Version: $VERSION"

# Tag the image with version number
docker tag webapi:tmp webapi:$VERSION
echo "Image tagged as webapi:$VERSION"

# Stop the container
docker stop webapi-tmp
echo "Webapi container stopped"
